### ISSUE TITLE
[ISSUE] Code -Check

### ISSUE THREAD

**Issue by iBadr49** [driezie/connect-your-tribe-profile-card#2]
[ X ]  Je hebt je visitekaartje gemaakt met Node
[ X ] Je kaartje gebruikt gegevens uit de REST API op whois.fdnd.nl
[ X ] Je kaartje is gepubliceerd via cyclic.sh
[ X ] Parials gerbruikt

Extra : Gebruik het  h1 -element alleen voor de hoogste kop (alle h1-elementen worden door veel screenreaders en andere tools als hoogste kop behandeld

**Comment by driezie** [comment]
Kan je voor mij duidelijk aangeven wat je met die extra bedoeld door middel van bronnen en perma-link?

**Comment by iBadr49** [comment]
https://github.com/driezie/connect-your-tribe-profile-card/blob/26fe5c279fa11594189b8690fc7027a41cd88d86/views/index.ejs#L3-L13

Zoals ik al aangaf, het is gewoon een extra punt niet echt een fout/error je code ziet er goed uit. Ik merkte op dat je met een button begon. Voor mensen die **screenreaders** gebruiken (toegankelijkheid), is het belangrijk om te weten dat als de h1- niet bovenaan de pagina staat, dit de toegankelijkheid kan beïnvloeden. Screenreaders lezen doorgaans webpagina's van boven naar beneden en zien de eerste kop van het document (h1) als de hoofdtitel van de pagina.
