### ISSUE TITLE
[ISSUE]  Root op volgorde maken

### ISSUE THREAD

**Issue by TomDeeterink1** [driezie/connect-your-tribe-profile-card#3]
**Vertel over je issue**
In je root, zou ik * bovenaan in de code zetten, aangezien dit het eerste is dat aangeroepen wordt.

**Hoe kan ik deze issue herproduceren zodat ik het probleem krijg**
Stappen die je kan gebruiken.
1. Go to css, en kijk naar je root.

**Vertel wat er moet gebeuren**
Zorg dat je root duidelijk op chronologische volgorde is.
<img width="502" alt="Schermafbeelding 2024-02-09 om 11 18 29" src="https://github.com/driezie/connect-your-tribe-profile-card/assets/144009665/4f37dd0b-9a3f-4dea-a61a-4213c4e44fc4">

**Comment by driezie** [comment]
Bedankt voor je issue. Ik heb even hierdoor gekeken en heb jou nog gevraagd voor extra vragen naar deze issue. Je zei dat hij de * boven de :root doet en de font class in de body doet die onderaan de :root komt. Dit maakt echter niks uit omdat de body en de * hetzelfde content de font geven, en als ik de * bovenaan doe werkt de value van die font niet meer.

**Conclusie:**
Ik vind het een niet nodige issue. Deze manier werkt even goed als jou manier. Daarom pas ik dit niet aan.

**Comment by driezie** [comment]
Duidelijk bedankt!

**Comment by joostf** [comment]
[like]  Joost Faber reacted to your message:
________________________________
