### ISSUE TITLE
[ISSUE] Script valt buiten de body

### ISSUE THREAD

**Issue by J3SS3HVA** [driezie/connect-your-tribe-profile-card#4]
Je `script` element waar je je script.js element linked staat buiten de body

```html
  </body>

  <script src="./js/script.js"></script>
  <script src="https://kit.fontawesome.com/b1b2df5e00.js" crossorigin="anonymous"></script>
</html>
```

wat je kan  doen is hem in de `head` zetten en hem de defer atribuut erin zetten.

`defer` zorgt ervoor dat de script alleen gelezen word als de pagina volledig geladen is

voorbeeld

`<script src="/script.js" defer></script>`

**Comment by driezie** [comment]
> This issue has been fixed in commit [26fe5c2](https://github.com/driezie/connect-your-tribe-profile-card/commit/26fe5c279fa11594189b8690fc7027a41cd88d86)  by @driezie
